settings:
  bullet: "-"
  listItemIndent: one
  emphasis: '_'
  strong: '*'
plugins:
  - remark-frontmatter
  - remark-preset-lint-consistent
  - remark-preset-lint-recommended
  - - remark-lint-list-item-indent
    - "space"
  - - remark-lint-emphasis-marker
    - "_"
  - - remark-lint-strong-marker
    - "*"
