_:
  clean: 'rimraf dist'
  build: 'rollup -c'
  cibuild_step1: 'rollup -c'
  test: &notests 'echo "{{name}}: No tests configured. Perhaps you''d like to do this?" && exit 0'
  pubtest: 'npm publish --registry http://localhost:6662'
  pubforce: 'npm publish'
  symlink: 'mkdir -p ./node_modules/@freesewing && cd ./node_modules/@freesewing && ln -s -f ../../../* . && cd -'
  start: 'rollup -c -w'
_types:
  pattern:
    netlify: 'echo "Not configured yet"'
    test: &test 'BABEL_ENV=production npx mocha tests/*.test.mjs --require @babel/register'
    testci: &testci "BABEL_ENV=production npx mocha tests/*.test.mjs --require @babel/register --reporter ../../tests/reporters/terse.js"
  plugin:
    test: *test
    testci: *testci
    prettier: "npx prettier --write 'src/*.js' 'tests/*.mjs'"
create-freesewing-pattern:
  clean: '!'
  nodebuild: '!'
  modulebuild: '!'
  cibuild_step1: '!'
  build: '!'
  test: *test
  testci: *testci
css-theme:
  cibuild_step1: 'npx node-sass --output-style compressed src/theme.scss dist/theme.css'
  build: 'npx node-sass --output-style compressed src/theme.scss dist/theme.css'
  watch: 'npx node-sass --watch --output-style compressed src/theme.scss dist/theme.css'
components:
  test: *notests
  storybook: 'start-storybook -p 6663'
  # react-scripts doesn't handle .mjs files correctly
  modulebuild: '!'
  clean: 'rimraf Blockquote && rimraf Draft && rimraf DraftConfigurator && rimraf Emblem && rimraf Example && rimraf Footer && rimraf Icon && rimraf Logo && rimraf Navbar && rimraf Ogol && rimraf Robot && rimraf SampleConfigurator && rimraf withGist && rimraf withLanguage && rimraf Workbench'
  cibuild_step2: 'rollup -c'
  build: 'rollup -c'
  watch: 'BABEL_ENV=production rollup -c -w -o dist/index.js -f cjs'
core:
  testonly: 'BABEL_ENV=production npx mocha tests/*.test.js'
  test: 'BABEL_ENV=production nyc -x node_modules -x tests/fixtures -x bin-pack npx mocha tests/*.test.js'
  testci: "BABEL_ENV=production npx mocha tests/*.test.js --require @babel/register --reporter ../../tests/reporters/terse.js"
  report: 'BABEL_ENV=production nyc report --reporter=html'
  coverage: 'BABEL_ENV=production nyc npm test && nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov'
i18n:
  # react-scripts doesn't handle .mjs files correctly
  modulebuild: '!'
  test: *test
  testci: *testci
  prebuild: 'node src/prebuild.mjs'
pattern-info:
  cibuild_step1: '!'
  cibuild_step2: 'node src/prebuild.js && rollup -c'
  prebuild: 'node src/prebuild.js'
utils:
  # react-scripts doesn't handle .mjs files correctly
  modulebuild: '!'
